### PR TITLE
Minor changes for QT5 support

### PR DESCRIPTION
**Pull request by dac922**
It compiles with QT4 and QT5 and plot(1:10) + zoom is working as well. I made no further tests yet.

### CODE REVIEW

**Comment by goffioul** [comment]
- wouldn't it better to use QMouseEvent::localPos()?
- qVariantFromValue<void*> can also be converted into QVariant::fromValue<void*>

**Comment by dac922** [comment]
- There is no QMouseEvent::localPos() in qt4 and I don't wanted to add #if's.
- QVariant::fromValue may work too. You mean:
  m_qobject->setProperty ("QtHandles::Object", QVariant::fromValue(this));
  and
  return v.value<Object*>();
  Edit: No, works with qt5, but not with qt4. reinterpret_cast is still necessary.

**Comment by goffioul** [comment]
I've merged your changes and made some minor modifications. It compiles for me on Qt4 (Fedora 18). Would you mind trying on Qt5?

**Comment by dac922** [comment]
Works so far, but on octave exit I get:
QSocketNotifier: Invalid socket 7 and type 'Read', disabling...
panic: Speicherzugriffsfehler -- stopping myself...

**Comment by goffioul** [comment]
Is it something I introduced? Or did it exist even with your patch?

**Comment by dac922** [comment]
It exist with my patch too. However, it's not reproducable with every run. Today I see no segfault. Some hours ago even the QSocketNotifier message was gone, but now it's back again.

**Comment by goffioul** [comment]
I'm not using Qt5 at the moment, but if possible, could you produce a backtrace with gdb, for the record?

**Pull request merged**
